define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Scan generated by Appery.io
     * @module Scan
     */

    APP.controller('Scan', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            var userData = Apperyio.get("dataStorage");
            $scope.user = userData.current;
            $scope.buttonCheck = false;

        };

        /**
         * @function scan_search
         */
        $scope.scan_search = function() {
            $scope.response = "";
            $scope.response1 = "";
            $scope.response2 = "";
            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            //var requestData = {};
            /*|button_mapping|onbeforesend|FD4F08A4-5809-4F2F-6E9E-74EE24B9E0E9||9137|*/

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("Barcode_scan")( /*requestData*/ ).then( /*|service_bookmark|bookmark|FD4F08A4-5809-4F2F-6E9E-74EE24B9E0E9||4945|*/

            function(success) { // success callback
                (function mapping5713(success, $scope) {
                    var code_scope = $scope.code;
                    code_scope = success.text;
                    $scope.code = code_scope; /*|button_mapping|onsuccess|FD4F08A4-5809-4F2F-6E9E-74EE24B9E0E9||5713|*/
                })(success, $scope);
                var requestData = {};
                requestData = (function mapping6917($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var code_scope = $scope.code;
                    requestData.params.MachineID = code_scope;

                    return requestData; /*CLICK TO EDIT MAPPING*/
                })($scope);

                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("Machine_search_service")(requestData).then(

                function(success) { // success callback
                    (function mapping6665(success, $scope) {
                        var machine_scope = $scope.machine;
                        _.set(machine_scope, 'login', success.data.Logging);
                        _.set(machine_scope, 'id', success.data.MachineID);
                        _.set(machine_scope, 'currentMachineUser', success.data.CurrentUser);
                        _.set(machine_scope, 'currentMachineBooker', success.data.CurrentBooker);
                        _.set(machine_scope, 'booked', success.data.Booking);
                        $scope.machine = machine_scope;
                        $scope.response = machine_scope.id;
                        $scope.response1 = machine_scope.login === true ? 'Yes' : 'No';
                        $scope.response2 = machine_scope.currentMachineUser == $scope.user.username ? 'Yes' : 'No'; /*CLICK TO EDIT MAPPING*/
                    })(success, $scope);
                }, function(error) { // callback to handle request error
                    var msg = "Unidentified";
                    $scope.response = msg;
                    var msg2 = "Unknown";
                    $scope.response1 = msg2;
                    $scope.response2 = msg2;

                });
            });

        };

        /**
         * @function requestLogin
         */
        $scope.requestLogin = function() {
            $scope.machineLogin = true;
            $scope.machine.login = $scope.machineLogin;
            $scope.newUser = $scope.user.username;
            $scope.updateLogging();
        };

        /**
         * @function requestLogout
         */
        $scope.requestLogout = function() {
            $scope.machineLogin = false;
            $scope.machine.login = $scope.machineLogin;
            $scope.newUser = "";
            $scope.updateLogging();

        };

        /**
         * @function updateLogging
         */
        $scope.updateLogging = function() {
            var requestData = {};
            requestData = (function mapping8535($scope) {
                var requestData = {};
                requestData.params = {};
                var machine_scope = $scope.machine;
                var newUser_scope = $scope.newUser;
                var machineLogin_scope = $scope.machineLogin;
                requestData.params.MachineID = machine_scope.id;
                requestData.params.User = newUser_scope;
                requestData.params.login = machineLogin_scope;

                return requestData; /*|button_mapping|onbeforesend|4DF5CE87-E610-7986-6D90-5C86627D4DC3||8535|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("Logging_update_service")(requestData).then( /*|service_bookmark|bookmark|4DF5CE87-E610-7986-6D90-5C86627D4DC3||9952|*/

            function(success) { // success callback
                (function mapping9198(success, $scope) {
                    var machine_scope = $scope.machine;
                    _.set(machine_scope, 'login', success.data.Logging);
                    _.set(machine_scope, 'id', success.data.MachineID);
                    _.set(machine_scope, 'currentMachineUser', success.data.CurrentUser);
                    _.set(machine_scope, 'type', success.data.MachineType);
                    _.set(machine_scope, 'booked', success.data.Booking);
                    $scope.machine = machine_scope;
                    $scope.response = machine_scope.id;
                    $scope.response1 = machine_scope.login === true ? 'Yes' : 'No';
                    $scope.response2 = machine_scope.currentMachineUser == $scope.user.username ? 'Yes' : 'No'; /*|button_mapping|onsuccess|4DF5CE87-E610-7986-6D90-5C86627D4DC3||9198|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.machine = Apperyio.EntityAPI('Machine');
        $scope.response = Apperyio.EntityAPI('String');
        $scope.response2 = Apperyio.EntityAPI('String');
        $scope.user = Apperyio.EntityAPI('User');
        $scope.code = Apperyio.EntityAPI('String');
        $scope.login = Apperyio.EntityAPI('Boolean');
        $scope.newUser = Apperyio.EntityAPI('String');
        $scope.buttonCheck = Apperyio.EntityAPI('Boolean');
        $scope.machineLogin = Apperyio.EntityAPI('Boolean');
    }

});