define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Register generated by Appery.io
     * @module Register
     */

    APP.controller('Register', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * @function register
         */
        $scope.register = function() {
            var requestData = {};
            requestData = (function mapping3486($scope) {
                var requestData = {};
                requestData.params = Apperyio.EntityAPI('RegisterNewUser_service.request.query', undefined, true);

                var user_scope = $scope.user;
                requestData.params.username = user_scope.username;
                requestData.params.password = user_scope.password;
                requestData.params.email = user_scope.email;
                requestData.params.country = user_scope.country;

                return requestData; /*|button_mapping|onbeforesend|68E55BC9-14C9-4D15-86F4-8C548E9D8CE3||3486|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("RegisterNewUser_service")(requestData).then( /*|service_bookmark|bookmark|68E55BC9-14C9-4D15-86F4-8C548E9D8CE3||8699|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|68E55BC9-14C9-4D15-86F4-8C548E9D8CE3||3373|*/

                var userData = Apperyio.get("dataStorage");
                userData.current = success.data;

                Apperyio.navigateTo("Welcome", {});

            }, function(error) { // callback to handle request error
                var userData = Apperyio.get("dataStorage");
                userData.message = error.data.message;

                var modalOptions = { // About Ionic Modal: https://devcenter.appery.io/documentation/angularjs/screens/#Modal_screen
                    animation: 'slide-in-up',
                    // The animation to show & hide with
                    focusFirstInput: false,
                    // Whether to autofocus the first input of the modal when shown
                    backdropClickToClose: true,
                    // Whether to close the modal on clicking the backdrop
                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                };

                Apperyio.get('Modals').loadModal("MessagePopup").then(

                function(modalInstance) {
                    modalInstance.open(modalOptions).then(function(modal) {
                        modal.scope.modal = modal;
                        modal.show();
                    });
                }, function(error) {
                    console.log(error);
                });

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.user = Apperyio.EntityAPI('User');
    }

});