define(['require', 'app'], function(require, APP) {

    /**
     * Controller for MachineList generated by Appery.io
     * @module MachineList
     */

    APP.controller('MachineList', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            var requestData = {}; /*|button_mapping|onbeforesend|04C2DD62-E2E5-2BC6-2E77-25DA9D492208||7987|*/

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("loadMachinesScript_service")(requestData).then( /*|service_bookmark|bookmark|04C2DD62-E2E5-2BC6-2E77-25DA9D492208||4548|*/

            function(success) { // success callback
                (function mapping7616(success, $scope) {
                    var machineList_scope = $scope.machineList;
                    for (var i = 0, l = success.data.length; i < l; i++) {
                        _.set(machineList_scope, '[' + i + '].id', success.data[i].MachineID);
                        _.set(machineList_scope, '[' + i + '].currentMachineUser', success.data[i].CurrentUser);
                        _.set(machineList_scope, '[' + i + '].currentMachineBooker', success.data[i].CurrentBooker);
                        _.set(machineList_scope, '[' + i + '].type', success.data[i].MachineType);
                        _.set(machineList_scope, '[' + i + '].login', success.data[i].Logging);
                        _.set(machineList_scope, '[' + i + '].booked', success.data[i].Booking);
                    }
                    $scope.machineList = machineList_scope; /*|button_mapping|onsuccess|04C2DD62-E2E5-2BC6-2E77-25DA9D492208||7616|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function DatePicker
         */
        $scope.DatePicker = function() {
            var requestData = {};
            requestData = (function mapping4032($scope) {
                var requestData = {};
                requestData.params = {};
                var DateValue_scope = $scope.DateValue;
                requestData.params.where = DateValue_scope;

                return requestData; /*|button_mapping|onbeforesend|89C6B232-1B1B-4EF4-33BF-790D7D3082B2||4032|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("UserDB_MachineState_query_service")(requestData).then( /*|service_bookmark|bookmark|89C6B232-1B1B-4EF4-33BF-790D7D3082B2||3320|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|89C6B232-1B1B-4EF4-33BF-790D7D3082B2||6260|*/

            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function Alreadybooked
         */
        $scope.Alreadybooked = function() {
            var $ionicPopup = Apperyio.get("$ionicPopup");
            var alertPopup = $ionicPopup.alert({
                title: 'Really?',
                template: "It is already booked."
            });
            alertPopup.then(function(res) {
                console.log("OK.. popup closed. Good.");
            });
        };

        /**
         * @function Youbookedit
         */
        $scope.Youbookedit = function() {
            var $ionicPopup = Apperyio.get("$ionicPopup");
            var alertPopup = $ionicPopup.alert({
                title: 'Success',
                template: "Your booking is completed."
            });
            alertPopup.then(function(res) {
                console.log("OK.. popup closed. Good.");
            });
        };

        /**
         * user controller variables
         */
        $scope.machineList = Apperyio.EntityAPI('MachineList');
        $scope.DateValue = Apperyio.EntityAPI('String');
    }

});