define(['require', 'app'], function(require, APP) {

    /**
     * Controller for MessagePopup generated by Appery.io
     * @module MessagePopup
     */

    APP.controller('MessagePopupController', ['$scope', 'Apperyio', MessagePopupController]);

    function MessagePopupController($scope, Apperyio) {

        // user controller functions
        // user controller variables
    }

});