define(['require'], function(require) {
    /**
     * Routing configuration generated by Appery.io
     */

    /**
     * Default route
     * @type {{redirectTo: string}}
     */
    var default_route = {
        redirectTo: '/Login.html'
    };

/**
     * Routing configuration object
     * @property {object} default                               - Default routing configuration
     * @property {string} default.redirectTo                    - Default routing URL
     * @property {object} when                                  - Routing configuration for different URLs
     * @property {object} when./                                - Routing configuration for "/" URL
     * @property {string} when./.redirectTo                     - Redirect to default routing URL
     * @property {object} when["/Login.html"]    - Routing configuration for /Login.html URL
     * @property {string} when["/Login.html"].c  - Controller for /Login.html URL
     * @property {string} when["/Login.html"].t  - Template for /Login.html URL
     * @property {string[]} when["/Login.html"].d  - Dependencies for /Login.html URL
     * @property {object} when["/Menu.html"]    - Routing configuration for /Menu.html URL
     * @property {string} when["/Menu.html"].c  - Controller for /Menu.html URL
     * @property {string} when["/Menu.html"].t  - Template for /Menu.html URL
     * @property {string[]} when["/Menu.html"].d  - Dependencies for /Menu.html URL
     * @property {object} when["/Register.html"]    - Routing configuration for /Register.html URL
     * @property {string} when["/Register.html"].c  - Controller for /Register.html URL
     * @property {string} when["/Register.html"].t  - Template for /Register.html URL
     * @property {string[]} when["/Register.html"].d  - Dependencies for /Register.html URL
     * @property {object} when["/MachineList.html"]    - Routing configuration for /MachineList.html URL
     * @property {string} when["/MachineList.html"].c  - Controller for /MachineList.html URL
     * @property {string} when["/MachineList.html"].t  - Template for /MachineList.html URL
     * @property {string[]} when["/MachineList.html"].d  - Dependencies for /MachineList.html URL
     * @property {object} when["/MachineList.html"]    - Routing configuration for /MachineList.html URL
     * @property {string} when["/MachineList.html"].c  - Controller for /MachineList.html URL
     * @property {string} when["/MachineList.html"].t  - Template for /MachineList.html URL
     * @property {string[]} when["/MachineList.html"].d  - Dependencies for /MachineList.html URL
     * @property {object} when["/Scan.html"]    - Routing configuration for /Scan.html URL
     * @property {string} when["/Scan.html"].c  - Controller for /Scan.html URL
     * @property {string} when["/Scan.html"].t  - Template for /Scan.html URL
     * @property {string[]} when["/Scan.html"].d  - Dependencies for /Scan.html URL
     * @property {object} when["/Charts_update.html"]    - Routing configuration for /Charts_update.html URL
     * @property {string} when["/Charts_update.html"].c  - Controller for /Charts_update.html URL
     * @property {string} when["/Charts_update.html"].t  - Template for /Charts_update.html URL
     * @property {string[]} when["/Charts_update.html"].d  - Dependencies for /Charts_update.html URL
     * @property {object} when["/MachineOverview.html"]    - Routing configuration for /MachineOverview.html URL
     * @property {string} when["/MachineOverview.html"].c  - Controller for /MachineOverview.html URL
     * @property {string} when["/MachineOverview.html"].t  - Template for /MachineOverview.html URL
     * @property {string[]} when["/MachineOverview.html"].d  - Dependencies for /MachineOverview.html URL
     * @property {object} when["/Account.html"]    - Routing configuration for /Account.html URL
     * @property {string} when["/Account.html"].c  - Controller for /Account.html URL
     * @property {string} when["/Account.html"].t  - Template for /Account.html URL
     * @property {string[]} when["/Account.html"].d  - Dependencies for /Account.html URL
     * @property {object} when["/weather.html"]    - Routing configuration for /weather.html URL
     * @property {string} when["/weather.html"].c  - Controller for /weather.html URL
     * @property {string} when["/weather.html"].t  - Template for /weather.html URL
     * @property {string[]} when["/weather.html"].d  - Dependencies for /weather.html URL

     * @property {object} otherwise                             - Routing configuration for another URL
     * @property {object} otherwise.redirectTo                  - Redirect to default routing URL
     * @property {object} route_names                           - Route aliases
     * @property {string} route_names.["Login"]  - "Login" is an alias for "/Login.html" routing
     * @property {string} route_names.["Menu"]  - "Menu" is an alias for "/Menu.html" routing
     * @property {string} route_names.["Register"]  - "Register" is an alias for "/Register.html" routing
     * @property {string} route_names.["MachineList"]  - "MachineList" is an alias for "/MachineList.html" routing
     * @property {string} route_names.["MachineList_44654"]  - "MachineList_44654" is an alias for "/MachineList.html" routing
     * @property {string} route_names.["Scan"]  - "Scan" is an alias for "/Scan.html" routing
     * @property {string} route_names.["Charts"]  - "Charts" is an alias for "/Charts_update.html" routing
     * @property {string} route_names.["MachineOverview"]  - "MachineOverview" is an alias for "/MachineOverview.html" routing
     * @property {string} route_names.["Account"]  - "Account" is an alias for "/Account.html" routing
     * @property {string} route_names.["weather"]  - "weather" is an alias for "/weather.html" routing

     */
    return {
    default:
        default_route, when: {
            '/': default_route,
            '/Login.html': {
                c: '$Login/LoginController',
                t: '$Login/LoginTemplate.html',
                d: []
            },
            '/Menu.html': {
                c: '$Menu/MenuController',
                t: '$Menu/MenuTemplate.html',
                d: []
            },
            '/Register.html': {
                c: '$Register/RegisterController',
                t: '$Register/RegisterTemplate.html',
                d: []
            },
            '/MachineList.html': {
                c: '$MachineList/MachineListController',
                t: '$MachineList/MachineListTemplate.html',
                d: []
            },
            '/Scan.html': {
                c: '$Scan/ScanController',
                t: '$Scan/ScanTemplate.html',
                d: []
            },
            '/Charts_update.html': {
                c: '$Charts_update/Charts_updateController',
                t: '$Charts_update/Charts_updateTemplate.html',
                d: []
            },
            '/MachineOverview.html': {
                c: '$MachineOverview/MachineOverviewController',
                t: '$MachineOverview/MachineOverviewTemplate.html',
                d: []
            },
            '/Account.html': {
                c: '$Account/AccountController',
                t: '$Account/AccountTemplate.html',
                d: []
            },

        },
        otherwise: default_route,
        route_names: {
            'Login': '/Login.html',
            'Menu': '/Menu.html',
            'Register': '/Register.html',
            'MachineList': '/MachineList.html',
            'MachineList_44654': '/MachineList.html',
            'Scan': '/Scan.html',
            'Charts': '/Charts_update.html',
            'MachineOverview': '/MachineOverview.html',
            'Account': '/Account.html',
            'weather': '/weather.html'

        }
    };
});