define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Login generated by Appery.io
     * @module Login
     */

    APP.controller('Login', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * @function login
         */
        $scope.login = function() {
            var requestData = {};
            requestData = (function mapping4383($scope) {
                var requestData = {};
                requestData.params = {};
                var user_scope = $scope.user;
                requestData.params.username = user_scope.username;
                requestData.params.password = user_scope.password;

                return requestData; /*|button_mapping|onbeforesend|C942FD1C-D22E-4CB4-BD3A-93C06FBF6BD7||4383|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LoginUser_service")(requestData).then( /*|service_bookmark|bookmark|C942FD1C-D22E-4CB4-BD3A-93C06FBF6BD7||1044|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|C942FD1C-D22E-4CB4-BD3A-93C06FBF6BD7||2693|*/

                var userData = Apperyio.get("dataStorage");
                userData.current = success.data;
                Apperyio.navigateTo("Menu", {});

            }, function(error) { // callback to handle request error

                var modalOptions = { // About Ionic Modal: https://devcenter.appery.io/documentation/angularjs/screens/#Modal_screen
                    animation: 'slide-in-up',
                    // The animation to show & hide with
                    focusFirstInput: false,
                    // Whether to autofocus the first input of the modal when shown
                    backdropClickToClose: true,
                    // Whether to close the modal on clicking the backdrop
                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                };

                Apperyio.get('Modals').loadModal("MessagePopup").then(

                function(modalInstance) {
                    modalInstance.open(modalOptions).then(function(modal) {
                        modal.scope.modal = modal;
                        modal.show();
                    });
                }, function(error) {
                    console.log(error);
                });

            }, function(notify) { // notify callback, can fire few times
            });
        };

        /**
         * user controller variables
         */
        $scope.user = Apperyio.EntityAPI('User');
    }

});