define(['require', 'app'], function(require, APP) {

    /**
     * Controller for MachineOverview generated by Appery.io
     * @module MachineOverview
     */

    APP.controller('MachineOverview', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            var requestData = {};
            requestData = (function mapping1708($scope) {
                var requestData = {};
                requestData.params = {};
                var Dateandtimestart_scope = $scope.Dateandtimestart;
                requestData.params.where = Dateandtimestart_scope;

                return requestData; /*|button_mapping|onbeforesend|36FF2A6B-13B7-ADDF-4B50-7CB0E4373BAF||1708|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("UserDB_MachineState_query_service")(requestData).then( /*|service_bookmark|bookmark|36FF2A6B-13B7-ADDF-4B50-7CB0E4373BAF||9408|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|36FF2A6B-13B7-ADDF-4B50-7CB0E4373BAF||5538|*/

            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.Dateandtimestart = Apperyio.EntityAPI('String');
        $scope.Dateandtimeend = Apperyio.EntityAPI('String');
    }

});